name = "bank"

# Cloudflare Pages site deployment settings
compatibility_date = "2026-07-07"
pages_build_output_dir = "dist"

[build]
command = "npm run build"
upload.format = "service-worker"

[site]
bucket = "dist"

[functions]
# Pages Functions path
directory = "functions"

[env.production]
# Add any production-specific variables here
